import type { ApiRouteContract } from "@providers/openapi/index.js";
import {
	AddCharacterTreasuryPreviewResponseSchema,
	AddCharacterTreasuryRequestSchema,
	AddCharacterTreasuryResponseSchema,
	CharacterTreasuryResponseSchema,
	ConvertCharacterTreasuryRequestSchema,
	ConvertCharacterTreasuryResponseSchema,
	InsufficientDenominationResponseSchema,
	InsufficientFundsResponseSchema,
	SpendCharacterTreasuryPreviewResponseSchema,
	SpendCharacterTreasuryRequestSchema,
	SpendCharacterTreasuryResponseSchema,
} from "../types/index.js";
import {
	CharacterTreasuryPathParamsSchema,
	inventoryTreasurySchemaImports,
	inventoryTreasuryTypeImports,
	TreasuryErrorResponseSchema,
} from "./contract-support.js";

export const inventoryTreasuryRouteContracts = [
	{
		method: "get",
		operationId: "getCharacterTreasury",
		path: "/api/characters/:characterId/treasury",
		pathParams: CharacterTreasuryPathParamsSchema,
		responses: {
			200: { description: "Character treasury", schema: CharacterTreasuryResponseSchema },
			400: { description: "Invalid character path", schema: TreasuryErrorResponseSchema },
			404: { description: "Character not found", schema: TreasuryErrorResponseSchema },
		},
		summary: "Get character treasury",
		tags: ["characters", "treasury"],
		client: {
			functionName: "getCharacterTreasury",
			imports: [...inventoryTreasuryTypeImports, ...inventoryTreasurySchemaImports],
			pathParamsType: "{ characterId: string }",
			responseParser: "CharacterTreasuryResponseSchema",
			responseType: "CharacterTreasuryResponse",
		},
	},
	{
		method: "put",
		operationId: "addCharacterTreasury",
		path: "/api/characters/:characterId/treasury",
		pathParams: CharacterTreasuryPathParamsSchema,
		requestBody: AddCharacterTreasuryRequestSchema,
		responses: {
			200: {
				description: "Updated character treasury",
				schema: AddCharacterTreasuryResponseSchema,
			},
			400: { description: "Invalid treasury add operation", schema: TreasuryErrorResponseSchema },
			404: { description: "Character not found", schema: TreasuryErrorResponseSchema },
		},
		summary: "Add funds to character treasury",
		tags: ["characters", "treasury"],
		client: {
			functionName: "addCharacterTreasury",
			imports: [...inventoryTreasuryTypeImports, ...inventoryTreasurySchemaImports],
			pathParamsType: "{ characterId: string }",
			requestBodyType: "AddCharacterTreasuryRequest",
			responseParser: "AddCharacterTreasuryResponseSchema",
			responseType: "AddCharacterTreasuryResponse",
		},
	},
	{
		method: "post",
		operationId: "spendCharacterTreasury",
		path: "/api/characters/:characterId/treasury/spend",
		pathParams: CharacterTreasuryPathParamsSchema,
		requestBody: SpendCharacterTreasuryRequestSchema,
		responses: {
			200: {
				description: "Updated character treasury",
				schema: SpendCharacterTreasuryResponseSchema,
			},
			400: { description: "Invalid treasury spend operation", schema: TreasuryErrorResponseSchema },
			404: { description: "Character not found", schema: TreasuryErrorResponseSchema },
			409: { description: "Insufficient funds", schema: InsufficientFundsResponseSchema },
		},
		summary: "Spend character treasury funds",
		tags: ["characters", "treasury"],
		client: {
			functionName: "spendCharacterTreasury",
			imports: [...inventoryTreasuryTypeImports, ...inventoryTreasurySchemaImports],
			pathParamsType: "{ characterId: string }",
			requestBodyType: "SpendCharacterTreasuryRequest",
			responseParser: "SpendCharacterTreasuryResponseSchema",
			responseType: "SpendCharacterTreasuryResponse",
		},
	},
	{
		method: "post",
		operationId: "convertCharacterTreasury",
		path: "/api/characters/:characterId/treasury/convert",
		pathParams: CharacterTreasuryPathParamsSchema,
		requestBody: ConvertCharacterTreasuryRequestSchema,
		responses: {
			200: {
				description: "Updated character treasury",
				schema: ConvertCharacterTreasuryResponseSchema,
			},
			400: { description: "Invalid treasury conversion", schema: TreasuryErrorResponseSchema },
			404: { description: "Character not found", schema: TreasuryErrorResponseSchema },
			409: {
				description: "Insufficient source denomination",
				schema: InsufficientDenominationResponseSchema,
			},
		},
		summary: "Convert character treasury denomination",
		tags: ["characters", "treasury"],
		client: {
			functionName: "convertCharacterTreasury",
			imports: [...inventoryTreasuryTypeImports, ...inventoryTreasurySchemaImports],
			pathParamsType: "{ characterId: string }",
			requestBodyType: "ConvertCharacterTreasuryRequest",
			responseParser: "ConvertCharacterTreasuryResponseSchema",
			responseType: "ConvertCharacterTreasuryResponse",
		},
	},
	{
		method: "post",
		operationId: "previewAddCharacterTreasury",
		path: "/api/characters/:characterId/treasury/preview/add",
		pathParams: CharacterTreasuryPathParamsSchema,
		requestBody: AddCharacterTreasuryRequestSchema,
		responses: {
			200: {
				description: "Character treasury add preview",
				schema: AddCharacterTreasuryPreviewResponseSchema,
			},
			400: { description: "Invalid treasury add preview", schema: TreasuryErrorResponseSchema },
			404: { description: "Character not found", schema: TreasuryErrorResponseSchema },
		},
		summary: "Preview adding character treasury funds",
		tags: ["characters", "treasury"],
		client: {
			functionName: "previewAddCharacterTreasury",
			imports: [...inventoryTreasuryTypeImports, ...inventoryTreasurySchemaImports],
			pathParamsType: "{ characterId: string }",
			requestBodyType: "AddCharacterTreasuryRequest",
			responseParser: "AddCharacterTreasuryPreviewResponseSchema",
			responseType: "AddCharacterTreasuryPreviewResponse",
		},
	},
	{
		method: "post",
		operationId: "previewSpendCharacterTreasury",
		path: "/api/characters/:characterId/treasury/preview/spend",
		pathParams: CharacterTreasuryPathParamsSchema,
		requestBody: SpendCharacterTreasuryRequestSchema,
		responses: {
			200: {
				description: "Character treasury spend preview",
				schema: SpendCharacterTreasuryPreviewResponseSchema,
			},
			400: { description: "Invalid treasury spend preview", schema: TreasuryErrorResponseSchema },
			404: { description: "Character not found", schema: TreasuryErrorResponseSchema },
		},
		summary: "Preview spending character treasury funds",
		tags: ["characters", "treasury"],
		client: {
			functionName: "previewSpendCharacterTreasury",
			imports: [...inventoryTreasuryTypeImports, ...inventoryTreasurySchemaImports],
			pathParamsType: "{ characterId: string }",
			requestBodyType: "SpendCharacterTreasuryRequest",
			responseParser: "SpendCharacterTreasuryPreviewResponseSchema",
			responseType: "SpendCharacterTreasuryPreviewResponse",
		},
	},
] as const satisfies readonly ApiRouteContract[];
