import { execFileSync } from "node:child_process";
import { existsSync } from "node:fs";
import { resolve } from "node:path";
import type { ApiClientContract, ApiRouteContract } from "@providers/openapi/index.js";

export function mergeUsedImports(
	routes: readonly ApiRouteContract[],
	usedNames: (client: ApiClientContract) => readonly string[],
) {
	const imports = routes.flatMap((route) => {
		const client = requiredClient(route);
		const names = new Set(usedNames(client));
		return (client.imports ?? []).map((spec) => ({
			...spec,
			names: spec.names.filter((name) => names.has(name)),
		}));
	});
	return mergeImports(imports.filter((spec) => spec.names.length > 0));
}

export function importedTypeNames(
	routes: readonly ApiRouteContract[],
	usedNames: (client: ApiClientContract) => readonly string[],
) {
	const names = new Set(
		routes.flatMap((route) => {
			const client = requiredClient(route);
			return usedNames(client);
		}),
	);
	return Array.from(
		new Set(
			routes.flatMap((route) =>
				(route.client?.imports ?? [])
					.filter((spec) => spec.kind !== "value")
					.flatMap((spec) => spec.names.filter((name) => names.has(name))),
			),
		),
	).sort();
}

export function identifiersReferencedBy(
	value: string | undefined,
	client: ApiClientContract,
	kind?: "value",
) {
	if (!value) return [];
	const identifiers = new Set(value.match(/[A-Za-z_$][A-Za-z0-9_$]*/g) ?? []);
	return (client.imports ?? [])
		.filter((spec) => kind === undefined || spec.kind === kind)
		.flatMap((spec) => spec.names.filter((name) => identifiers.has(name)));
}

export function mergeImports(
	imports: readonly { kind?: "type" | "value"; module: string; names: readonly string[] }[],
	forceTypeExports = false,
) {
	const importsByModule = new Map<
		string,
		{ kind: "type" | "value"; module: string; names: Set<string> }
	>();
	for (const spec of imports) {
		const kind = spec.kind ?? "type";
		const key = `${kind}:${spec.module}`;
		const entry = importsByModule.get(key) ?? {
			kind,
			module: spec.module,
			names: new Set<string>(),
		};
		for (const name of spec.names) entry.names.add(name);
		importsByModule.set(key, entry);
	}

	return Array.from(importsByModule.entries())
		.sort(([, left], [, right]) => {
			const moduleOrder = left.module.localeCompare(right.module);
			return moduleOrder === 0 ? left.kind.localeCompare(right.kind) : moduleOrder;
		})
		.map(([, spec]) => {
			const names = Array.from(spec.names).sort();
			const importStatement = namedImport(spec.kind, names, spec.module);
			if (spec.kind === "value" || !forceTypeExports) return importStatement;
			return `${importStatement}\nexport type ${namedExport(names, spec.module)};`;
		})
		.join("\n");
}

export function namedImport(kind: "type" | "value", names: readonly string[], module: string) {
	const prefix = kind === "value" ? "import" : "import type";
	return [
		`${prefix} {`,
		...names.map((name) => `\t${name},`),
		`} from ${JSON.stringify(module)};`,
	].join("\n");
}

export function namedExport(names: readonly string[], module: string) {
	return ["{", ...names.map((name) => `\t${name},`), `} from ${JSON.stringify(module)}`].join("\n");
}

export function requiredClient(route: ApiRouteContract) {
	if (!route.client) throw new Error(`Route ${route.operationId} is missing client metadata.`);
	return route.client;
}

export function pathTemplate(path: string) {
	const template = path.replaceAll(
		/:([A-Za-z0-9_]+)/g,
		(_match, name: string) => `\${${"params."}${name}}`,
	);
	return `\`${template}\``;
}

export function methodParameters(client: ApiClientContract) {
	const params = [];
	if (client.pathParamsType) params.push(`params: ${client.pathParamsType}`);
	if (client.requestBodyType) params.push(`body: ${client.requestBodyType}`);
	params.push("options: ApiRequestOptions = {}");
	return params.join(", ");
}

export function mutationFunction(client: ApiClientContract) {
	if (client.pathParamsType && client.requestBodyType) {
		return `(variables: { params: ${client.pathParamsType}; body: ${client.requestBodyType} }) =>\n\t\t\tclient.${client.functionName}(variables.params, variables.body, options)`;
	}
	if (client.pathParamsType) {
		return `(params: ${client.pathParamsType}) =>\n\t\t\tclient.${client.functionName}(params, options)`;
	}
	if (client.requestBodyType) {
		return `(body: ${client.requestBodyType}) =>\n\t\t\tclient.${client.functionName}(body, options)`;
	}
	return `() => client.${client.functionName}(options)`;
}

export function generatedHeader() {
	return "/* This file is generated by scripts/generate-openapi.ts. Do not edit by hand. */";
}

export function formatGeneratedContent(content: string, relativePath: string, root: string) {
	const biomePath = resolve(root, "node_modules/.bin/biome");
	if (!existsSync(biomePath)) throw new Error("Biome is required to format generated artifacts.");
	return execFileSync(biomePath, ["format", "--stdin-file-path", relativePath], {
		cwd: root,
		encoding: "utf8",
		input: `${content}\n`,
	});
}

export function isGeneratedArtifact(file: string) {
	return file.endsWith(".generated.ts") || file.endsWith(".generated.json");
}

export function indent(value: string, level: number) {
	const prefix = "\t".repeat(level);
	return value
		.split("\n")
		.map((line) => (line ? `${prefix}${line}` : line))
		.join("\n");
}

export function toPascalCase(value: string) {
	return value
		.split(/[^A-Za-z0-9]+/)
		.filter(Boolean)
		.map((part) => `${part[0].toUpperCase()}${part.slice(1)}`)
		.join("");
}

export function importModulePath(statement: string) {
	return statement.match(/from "([^"]+)"/)?.[1] ?? statement;
}

export function isDefined<T>(value: T | undefined): value is T {
	return value !== undefined;
}
