import type { ApiRouteContract } from "@providers/openapi/index.js";
import {
	CharacterDetailResponseSchema,
	CharacterSpellSlotsResponseSchema,
	CreateCharacterRequestSchema,
	ListCharactersResponseSchema,
	RestoreCharacterSpellSlotRequestSchema,
	UpdateCharacterExperienceRequestSchema,
	UpdateCharacterHealthRequestSchema,
	UpdateCharacterHealthResponseSchema,
	UpdateCharacterLevelRequestSchema,
	UpdateCharacterNameRequestSchema,
	UpdateCharacterSpellSlotsRequestSchema,
	UseCharacterSpellSlotRequestSchema,
} from "../types/index.js";
import { characterSpellRouteContracts } from "./character-spell-contracts.js";
import {
	CharacterPathParamsSchema,
	characterSchemaImports,
	characterTypeImports,
	ErrorResponseSchema,
} from "./contract-support.js";

export const characterRouteContracts = [
	{
		method: "post",
		operationId: "createCharacter",
		path: "/api/characters",
		requestBody: CreateCharacterRequestSchema,
		responses: {
			201: { description: "Created character", schema: CharacterDetailResponseSchema },
			400: { description: "Invalid character data", schema: ErrorResponseSchema },
		},
		summary: "Create character",
		tags: ["characters"],
		client: {
			functionName: "createCharacter",
			imports: [...characterTypeImports, ...characterSchemaImports],
			requestBodyType: "CreateCharacterRequest",
			responseParser: "CharacterDetailResponseSchema",
			responseType: "CharacterDetailResponse",
		},
	},
	{
		method: "get",
		operationId: "listCharacters",
		path: "/api/characters",
		responses: {
			200: { description: "Characters", schema: ListCharactersResponseSchema },
		},
		summary: "List characters",
		tags: ["characters"],
		client: {
			functionName: "listCharacters",
			imports: [...characterTypeImports, ...characterSchemaImports],
			responseParser: "ListCharactersResponseSchema",
			responseType: "ListCharactersResponse",
		},
	},
	{
		method: "get",
		operationId: "getCharacter",
		path: "/api/characters/:characterId",
		pathParams: CharacterPathParamsSchema,
		responses: {
			200: { description: "Character detail", schema: CharacterDetailResponseSchema },
			404: { description: "Character not found", schema: ErrorResponseSchema },
		},
		summary: "Get character",
		tags: ["characters"],
		client: {
			functionName: "getCharacter",
			imports: [...characterTypeImports, ...characterSchemaImports],
			pathParamsType: "{ characterId: string }",
			responseParser: "CharacterDetailResponseSchema",
			responseType: "CharacterDetailResponse",
		},
	},
	{
		method: "put",
		operationId: "updateCharacterLevel",
		path: "/api/characters/:characterId/level",
		pathParams: CharacterPathParamsSchema,
		requestBody: UpdateCharacterLevelRequestSchema,
		responses: {
			200: { description: "Updated character level", schema: CharacterDetailResponseSchema },
			400: { description: "Invalid character level", schema: ErrorResponseSchema },
			404: { description: "Character not found", schema: ErrorResponseSchema },
		},
		summary: "Update character level",
		tags: ["characters"],
		client: {
			functionName: "updateCharacterLevel",
			imports: [...characterTypeImports, ...characterSchemaImports],
			pathParamsType: "{ characterId: string }",
			requestBodyType: "UpdateCharacterLevelRequest",
			responseParser: "CharacterDetailResponseSchema",
			responseType: "CharacterDetailResponse",
		},
	},
	{
		method: "put",
		operationId: "updateCharacterName",
		path: "/api/characters/:characterId/name",
		pathParams: CharacterPathParamsSchema,
		requestBody: UpdateCharacterNameRequestSchema,
		responses: {
			200: { description: "Updated character name", schema: CharacterDetailResponseSchema },
			400: { description: "Invalid character name", schema: ErrorResponseSchema },
			404: { description: "Character not found", schema: ErrorResponseSchema },
		},
		summary: "Update character name",
		tags: ["characters"],
		client: {
			functionName: "updateCharacterName",
			imports: [...characterTypeImports, ...characterSchemaImports],
			pathParamsType: "{ characterId: string }",
			requestBodyType: "UpdateCharacterNameRequest",
			responseParser: "CharacterDetailResponseSchema",
			responseType: "CharacterDetailResponse",
		},
	},
	{
		method: "put",
		operationId: "updateCharacterExperience",
		path: "/api/characters/:characterId/experience",
		pathParams: CharacterPathParamsSchema,
		requestBody: UpdateCharacterExperienceRequestSchema,
		responses: {
			200: { description: "Updated character experience", schema: CharacterDetailResponseSchema },
			400: { description: "Invalid character experience", schema: ErrorResponseSchema },
			404: { description: "Character not found", schema: ErrorResponseSchema },
		},
		summary: "Update character experience",
		tags: ["characters"],
		client: {
			functionName: "updateCharacterExperience",
			imports: [...characterTypeImports, ...characterSchemaImports],
			pathParamsType: "{ characterId: string }",
			requestBodyType: "UpdateCharacterExperienceRequest",
			responseParser: "CharacterDetailResponseSchema",
			responseType: "CharacterDetailResponse",
		},
	},
	{
		method: "put",
		operationId: "updateCharacterHealth",
		path: "/api/characters/:characterId/health",
		pathParams: CharacterPathParamsSchema,
		requestBody: UpdateCharacterHealthRequestSchema,
		responses: {
			200: {
				description: "Updated character health",
				schema: UpdateCharacterHealthResponseSchema,
			},
			400: { description: "Invalid health data", schema: ErrorResponseSchema },
			404: { description: "Character not found", schema: ErrorResponseSchema },
		},
		summary: "Update character health",
		tags: ["characters"],
		client: {
			functionName: "updateCharacterHealth",
			imports: [...characterTypeImports, ...characterSchemaImports],
			pathParamsType: "{ characterId: string }",
			requestBodyType: "UpdateCharacterHealthRequest",
			responseParser: "UpdateCharacterHealthResponseSchema",
			responseType: "UpdateCharacterHealthResponse",
		},
	},
	{
		method: "get",
		operationId: "getCharacterSpellSlots",
		path: "/api/characters/:characterId/spell-slots",
		pathParams: CharacterPathParamsSchema,
		responses: {
			200: {
				description: "Character spell slots",
				schema: CharacterSpellSlotsResponseSchema,
			},
			404: { description: "Character not found", schema: ErrorResponseSchema },
		},
		summary: "Get character spell slots",
		tags: ["characters"],
		client: {
			functionName: "getCharacterSpellSlots",
			imports: [...characterTypeImports, ...characterSchemaImports],
			pathParamsType: "{ characterId: string }",
			responseParser: "CharacterSpellSlotsResponseSchema",
			responseType: "CharacterSpellSlotsResponse",
		},
	},
	{
		method: "put",
		operationId: "updateCharacterSpellSlots",
		path: "/api/characters/:characterId/spell-slots",
		pathParams: CharacterPathParamsSchema,
		requestBody: UpdateCharacterSpellSlotsRequestSchema,
		responses: {
			200: {
				description: "Updated character spell slots",
				schema: CharacterSpellSlotsResponseSchema,
			},
			400: { description: "Invalid spell slot data", schema: ErrorResponseSchema },
			404: { description: "Character not found", schema: ErrorResponseSchema },
		},
		summary: "Update character spell slots",
		tags: ["characters"],
		client: {
			functionName: "updateCharacterSpellSlots",
			imports: [...characterTypeImports, ...characterSchemaImports],
			pathParamsType: "{ characterId: string }",
			requestBodyType: "UpdateCharacterSpellSlotsRequest",
			responseParser: "CharacterSpellSlotsResponseSchema",
			responseType: "CharacterSpellSlotsResponse",
		},
	},
	{
		method: "post",
		operationId: "useCharacterSpellSlot",
		path: "/api/characters/:characterId/spell-slots/use",
		pathParams: CharacterPathParamsSchema,
		requestBody: UseCharacterSpellSlotRequestSchema,
		responses: {
			200: { description: "Used character spell slot", schema: CharacterSpellSlotsResponseSchema },
			400: { description: "Spell slot unavailable", schema: ErrorResponseSchema },
			404: { description: "Character not found", schema: ErrorResponseSchema },
		},
		summary: "Use character spell slot",
		tags: ["characters"],
		client: {
			functionName: "useCharacterSpellSlot",
			imports: [...characterTypeImports, ...characterSchemaImports],
			pathParamsType: "{ characterId: string }",
			requestBodyType: "UseCharacterSpellSlotRequest",
			responseParser: "CharacterSpellSlotsResponseSchema",
			responseType: "CharacterSpellSlotsResponse",
		},
	},
	{
		method: "post",
		operationId: "restoreCharacterSpellSlot",
		path: "/api/characters/:characterId/spell-slots/restore",
		pathParams: CharacterPathParamsSchema,
		requestBody: RestoreCharacterSpellSlotRequestSchema,
		responses: {
			200: {
				description: "Restored character spell slot",
				schema: CharacterSpellSlotsResponseSchema,
			},
			400: { description: "Spell slot unavailable", schema: ErrorResponseSchema },
			404: { description: "Character not found", schema: ErrorResponseSchema },
		},
		summary: "Restore character spell slot",
		tags: ["characters"],
		client: {
			functionName: "restoreCharacterSpellSlot",
			imports: [...characterTypeImports, ...characterSchemaImports],
			pathParamsType: "{ characterId: string }",
			requestBodyType: "RestoreCharacterSpellSlotRequest",
			responseParser: "CharacterSpellSlotsResponseSchema",
			responseType: "CharacterSpellSlotsResponse",
		},
	},
	{
		method: "post",
		operationId: "applyCharacterSpellSlotDefaults",
		path: "/api/characters/:characterId/spell-slots/apply-defaults",
		pathParams: CharacterPathParamsSchema,
		responses: {
			200: {
				description: "Applied D&D API spell slot defaults",
				schema: CharacterSpellSlotsResponseSchema,
			},
			404: { description: "Character not found", schema: ErrorResponseSchema },
			502: { description: "D&D API unavailable", schema: ErrorResponseSchema },
		},
		summary: "Apply character spell slot defaults",
		tags: ["characters"],
		client: {
			functionName: "applyCharacterSpellSlotDefaults",
			imports: [...characterTypeImports, ...characterSchemaImports],
			pathParamsType: "{ characterId: string }",
			responseParser: "CharacterSpellSlotsResponseSchema",
			responseType: "CharacterSpellSlotsResponse",
		},
	},
	...characterSpellRouteContracts,
] as const satisfies readonly ApiRouteContract[];
